---
downloads: ~/.ansible-downloads/

configure_dock: true
configure_dotfiles: true
configure_osx: true
configure_shell: true
configure_ssh: true
configure_sublime: false
configure_sudoers: false
configure_terminal: true

dockitems_remove:
  - "App Store"
  - FaceTime
  - Launchpad
  - Mail
  - Maps
  - Music
  - Podcasts
  - TV
dockitems_persist:
  - name: "System Preferences"
    path: "/System/Applications/System Preferences.app"
    pos: 1
  - name: "1Password 7"
    path: "/Applications/1Password 7.app"
    pos: 2
  - name: "Postbox"
    path: "/Applications/Postbox.app"
    pos: 3
  # Spacer at #4 (see tasks/dock.yml)
  - name: "Firefox Nightly"
    path: "/Applications/Firefox Nightly.app"
    pos: 4
  - name: "Firefox"
    path: "/Applications/Firefox.app"
    pos: 5
  - name: "Firefox Developer Edition"
    path: "/Applications/Firefox Developer Edition.app"
    pos: 6
  - name: "Safari"
    path: "/Applications/Safari.app"
    pos: 7
  - name: "Safari Technology Preview"
    path: "/Applications/Safari Technology Preview.app"
    pos: 8
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app"
    pos: 9
  - name: "Google Chrome Canary"
    path: "/Applications/Google Chrome Canary.app"
    pos: 10
  - name: "Google Chrome Dev"
    path: "/Applications/Google Chrome Dev.app"
    pos: 11
  # Spacer at #13 (see tasks/dock.yml)
  - name: "Sourcetree"
    path: "/Applications/Sourcetree.app"
    pos: 12
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
    pos: 13
  - name: "Xcode"
    path: "/Applications/Xcode.app"
    pos: 14
  - name: "Android Studio"
    path: "/Applications/Android Studio.app"
    pos: 15
  - name: "Sketch"
    path: "/Applications/Sketch.app"
    pos: 16
  - name: "Figma"
    path: "/Applications/Figma.app"
    pos: 17
  - name: "Terminal"
    path: "/System/Applications/Utilities/Terminal.app"
    pos: 18
  - name: "Postman"
    path: "/Applications/Postman.app"
    pos: 19
  - name: "Colour Contrast Analyser (CCA)"
    path: "/Applications/Colour Contrast Analyser (CCA).app"
    pos: 20
  # Spacer at #23 (see tasks/dock.yml)
  - name: "Contacts"
    path: "/System/Applications/Contacts.app"
    pos: 21
  - name: "Calendar"
    path: "/System/Applications/Calendar.app"
    pos: 22
  - name: "Obsidian"
    path: "/Applications/Obsidian.app"
    pos: 23
  - name: "Notion"
    path: "/Applications/Notion.app"
    pos: 24
  - name: "GoodNotes"
    path: "/Applications/GoodNotes.app"
    pos: 25
  - name: "Notes"
    path: "/System/Applications/Notes.app"
    pos: 26
  - name: "Reminders"
    path: "/System/Applications/Reminders.app"
    pos: 27
  # Spacer at #31 (see tasks/dock.yml)
  - name: "Photos"
    path: "/System/Applications/Photos.app"
    pos: 28
  - name: "Messages"
    path: "/System/Applications/Messages.app"
    pos: 29
  - name: "Discord"
    path: "/Applications/Discord.app"
    pos: 30
  - name: "Books"
    path: "/System/Applications/Books.app"
    pos: 31

sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/thomasmassmann/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/dotfiles
dotfiles_files:
  - .aliases
  - .gemrc
  - .gitconfig
  - .gitignore
  - .mrbob
  - .osx
  - .nuxtrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cocoapods
  - curl
  - docker-completion
  - gettext
  - git
  - gradle
  - grunt-completion
  - htop
  - node
  - nvm
  - mysql-client
  - mysql
  - nvm
  - openjdk
  - openldap
  - openssl
  - pip-completion
  - postgresql
  - pyenv
  - pyenv-virtualenv
  - python
  - python3
  - python@3.9
  - readline
  - sqlite
  - ssh-copy-id
  - tree
  - wget
  - yarn
  - zsh
  - zsh-completions
  - zsh-git-prompt
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - adoptopenjdk8
  - android-sdk
  - android-studio
  - appcleaner
  # Current version has a download error
  # - balsamiq-wireframes
  - chromedriver
  - colour-contrast-analyser
  - discord
  - docker
  - figma
  - firefox
  - firefox-developer-edition
  - firefox-nightly
  - google-chrome
  - google-chrome-canary
  - google-chrome-dev
  - gpg-suite
  - handbrake
  - istat-menus
  - kdiff3
  - kitematic
  - libreoffice
  - micro-snitch
  - moom
  - notion
  - obsidian
  - poedit
  - postbox
  - postman
  # - safari-technology-preview
  - sketch
  - slack
  - sourcetree
  - synology-drive
  - synology-photo-station-uploader
  - teamviewer
  - tnefs-enough
  - transmit4
  - tunnelblick
  - vagrant
  - virtualbox
  - visual-studio-code
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - id: 405580712
    name: "StuffIt Expander"
  - id: 408981434
    name: "iMovie"
  - id: 409183694
    name: "Keynote"
  - id: 409201541
    name: "Pages"
  - id: 409203825
    name: "Numbers"
  - id: 494803304
    name: "WiFi Explorer"
  - id: 497799835
    name: "Xcode"
  - id: 1153157709
    name: "Speedtest"
  - id: 1388020431
    name: "DevCleaner"
  - id: 1444383602
    name: "GoodNotes"
mas_uninstalled_apps:
  - id: 682658836
    name: "GarageBand"
mas_email: ""
mas_password: ""

osx_script: "~/.osx"

node_versions:
  - v10.14.2
  - v10.24.1
  - v12.16.2
  - v13.13.0
  - v14.15.1

node_default_version: v14.15.1

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: grunt
    state: present
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

zsh_theme_name: powerlevel9k
zsh_theme_repo: https://github.com/bhilburn/powerlevel9k.git

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
