---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - cocoapods
  - curl
  - docker-completion
  - gettext
  - git
  - gradle
  - grunt-completion
  - htop
  - node
  - nvm
  - mysql-client
  - mysql
  - openjdk
  - openldap
  - openssl
  - pip-completion
  - postgresql
  - pyenv
  - pyenv-virtualenv
  - python
  - python3
  - python@3.9
  - readline
  - sqlite
  - ssh-copy-id
  - tree
  - wget
  - yarn
  - zsh
  - zsh-completions
  - zsh-git-prompt
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - adoptopenjdk8
  - android-sdk
  - android-studio
  - appcleaner
  # Current version has a download error
  # - balsamiq-wireframes
  - chromedriver
  - colour-contrast-analyser
  - discord
  - docker
  - figma
  - firefox
  - firefox-developer-edition
  - firefox-nightly
  - google-chrome
  - google-chrome-canary
  - google-chrome-dev
  - gpg-suite
  - handbrake
  - istat-menus
  - kitematic
  - libreoffice
  - micro-snitch
  - moom
  - notion
  - obsidian
  - poedit
  - postbox
  - postman
  # - safari-technology-preview
  - sketch
  - slack
  - sourcetree
  - synology-drive
  - synology-photo-station-uploader
  - teamviewer
  - tnefs-enough
  - transmit4
  - tunnelblick
  - vagrant
  - virtualbox
  - visual-studio-code
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 405580712, name: "StuffIt Expander" }
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 494803304, name: "WiFi Explorer" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1153157709, name: "Speedtest" }
  - { id: 1388020431, name: "DevCleaner" }
  - { id: 1444383602, name: "GoodNotes" }
mas_uninstalled_apps:
  - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
