---
- name: Create a new ssh key pair
  block:
    - name: Decode private key
      shell: echo {{ item.key }} | base64 --decode
      register: ssh_private_key_decoded
      changed_when: false
      check_mode: false
      become: false

    - name: Create private key
      template:
        src: templates/ssh_key.j2
        dest: "~/.ssh/{{ item.id }}"
        mode: 0600
      become: false

    - name: Create public key
      template:
        src: templates/ssh_key_pub.j2
        dest: ~/.ssh/{{ item.id }}.pub
        mode: 0644
      become: false

    - name: Check if key is already in ssh agent
      command: "ssh-add -l | grep '/.ssh/{{ item.id }} ('"
      register: key_available
      changed_when: false
      check_mode: false
      ignore_errors: true
      become: false

    - name: Add key to ssh agent
      command: "ssh-add ~/.ssh/{{ item.id }}"
      changed_when: false
      check_mode: false
      when: "item.id|string not in key_available.stdout"
      ignore_errors: true
      become: false
