---
# Custom Terminal theme.
- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  copy:
    src: files/terminal/Solarized-Dark.terminal
    dest: /tmp/Solarized-Dark.terminal
  changed_when: false
  when: "'Solarized-Dark' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  command: open /tmp/Solarized-Dark.terminal
  changed_when: false
  when: "'Solarized-Dark' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string Solarized-Dark
    - defaults write com.apple.terminal 'Startup Window Settings' -string Solarized-Dark
  changed_when: false
  when: "'Solarized-Dark' not in terminal_theme.stdout"
